### ISSUE TITLE
where are vendor folder

### ISSUE THREAD

**Issue by stilllifee** [codeengineerr/pos#1]
error 

Warning: require(D:\xampp\htdocs\pos\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\pos\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'D:\xampp\htdocs\pos\bootstrap/../vendor/autoload.php' (include_path='.;D:\xampp\php\PEAR') in D:\xampp\htdocs\pos\bootstrap\autoload.php on line 17

**Comment by usman342** [comment]
facing this error kindly provide the vendor folder
Warning: require(C:\xampp\htdocs\pos\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\pos\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\pos\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\pos\bootstrap\autoload.php on line 17

**Comment by iftikharuddin** [comment]
Thanks for informing @stilllifee  @usman342  Vendor file added successfully.Actually it was placed in .gitignore file mistakenly.
