### ISSUE TITLE
# issue 2

### ISSUE THREAD

**Issue by usman342** [codeengineerr/pos#2]
![screenshot_3](https://cloud.githubusercontent.com/assets/10772390/15046577/ee818a0c-12f9-11e6-8827-7fcfdbe93299.png)

**Comment by iftikharuddin** [comment]
Did you imported the database files ?

**Comment by iftikharuddin** [comment]
@usman342 i got it , actually you have deleted all products you need to create atleast a product.Because when you insert a product it sends NULL value to DB , so you must have a product and you can add that from the dashboard.

**Comment by usman342** [comment]
OK Man
