### ISSUE TITLE
Import after Tables error.

### ISSUE THREAD

**Issue by tamilheartz** [codeengineerr/pos#3]
QueryException in Connection.php line 673:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pos.settings' doesn't exist (SQL: select * from `settings` where `settings`.`id` = 1 limit 1)

PDOException in Connection.php line 333:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pos.settings' doesn't exist

**Comment by wadleo** [comment]
@tamilheartz  have you check your mysql server, if the table exists from the terminal or a visual tool like phpmyadmin or mysql workbench?

**Comment by iftikharuddin** [comment]
@tamilheartz it exist in the post.sql.zip did you run the SQL separately?
